import 'package:flutter/material.dart';

class RecommendationAnalysisPage extends StatelessWidget {
  final String weather;
  final int happinessLevel;
  final String occasion;

  const RecommendationAnalysisPage({
    super.key,
    required this.weather,
    required this.happinessLevel,
    required this.occasion,
  });

  List<Color> _generatePalette() {
    List<Color> baseColors = [];

    // Weather-based color bias
    if (weather == "Sunny") {
      baseColors.addAll([Colors.yellow, Colors.orangeAccent]);
    } else if (weather == "Rainy") {
      baseColors.addAll([Colors.blueGrey, Colors.indigo]);
    } else if (weather == "Cloudy") {
      baseColors.addAll([Colors.grey, Colors.blueGrey]);
    } else if (weather == "Snowy") {
      baseColors.addAll([Colors.white, Colors.lightBlue]);
    } else if (weather == "Windy") {
      baseColors.addAll([Colors.lightGreen, Colors.teal]);
    }

    // Mood-based hue tone
    if (happinessLevel <= 1) {
      baseColors.addAll([Colors.redAccent]);
    } else if (happinessLevel == 2) {
      baseColors.addAll([Colors.orange]);
    } else if (happinessLevel == 3) {
      baseColors.addAll([Colors.greenAccent]);
    } else {
      baseColors.addAll([Colors.purple, Colors.pinkAccent]);
    }

    // Occasion bias (add one more tone)
    if (occasion == "Wedding") {
      baseColors.add(Colors.pink[100]!);
    } else if (occasion == "Work") {
      baseColors.add(Colors.blueGrey);
    } else if (occasion == "Vacation") {
      baseColors.add(Colors.cyanAccent);
    } else if (occasion == "Party") {
      baseColors.add(Colors.deepPurpleAccent);
    } else if (occasion == "Casual") {
      baseColors.add(Colors.lightGreenAccent);
    } else if (occasion == "School") {
      baseColors.add(Colors.amberAccent);
    }

    return baseColors.take(10).toList();
  }

  @override
  Widget build(BuildContext context) {
    final palette = _generatePalette();

    return Scaffold(
      backgroundColor: const Color(0xFFF9F6F3),
      appBar: AppBar(
        title: const Text("Today's Palette"),
        backgroundColor: const Color(0xFF3B2213),
        foregroundColor: Colors.white,
      ),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            const Text(
              "Based on your mood, weather, and occasion, you should wear:",
              style: TextStyle(fontSize: 18, fontFamily: 'Serif'),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            Wrap(
              spacing: 10,
              runSpacing: 10,
              children: palette
                  .map((color) => Container(
                width: 50,
                height: 50,
                decoration: BoxDecoration(
                  color: color,
                  shape: BoxShape.circle,
                  border: Border.all(color: Colors.black12),
                ),
              ))
                  .toList(),
            ),
            const SizedBox(height: 40),
            const Text(
              '✨ Generated by Beauty Buddy ✨',
              style: TextStyle(
                fontSize: 14,
                fontStyle: FontStyle.italic,
                color: Colors.grey,
              ),
            ),
          ],
        ),
      ),
    );
  }
}